[package]
name = "diffie_hellman"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
num = { version = "0.4.3", features = ["rand"] }
rand = "0.8.5"
